# Generated by Django 4.1.1 on 2022-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
