# Generated by Django 4.1.1 on 2022-09-22 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 17, 51, 37, 341090)),
        ),
    ]
